language: c
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFIGURE_FLAGS="--with-xgbsplay"
    - os: linux
      compiler: gcc
      env: CONFIGURE_FLAGS="--with-xgbsplay --enable-sharedlibgbs"
    - os: linux
      compiler: clang
      env: CONFIGURE_FLAGS="--with-xgbsplay"
    - os: linux
      compiler: clang
      env: CONFIGURE_FLAGS="--with-xgbsplay --enable-sharedlibgbs"
    - os: osx
      compiler: clang
      env: CONFIGURE_FLAGS=
script:
  - ./configure && make && make test
  - make distclean
  - make dist
addons:
  apt:
    packages:
      - libasound2-dev
      - libpulse-dev
      - libaudio-dev
      - libx11-dev
after_success:
  - bash <(curl -s https://codecov.io/bash)
